server:
  port: 8081

spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver