server:
  port: 8080

spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
